version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'monthly'
          day: 'monday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'
          - 'brightlayer-ui'

    - package-ecosystem: 'npm'
      directory: '/authentication-typescript'
      schedule:
          interval: 'monthly'
          day: 'monday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'
          - 'brightlayer-ui'

    - package-ecosystem: 'npm'
      directory: '/blank-typescript'
      schedule:
          interval: 'monthly'
          day: 'monday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'
          - 'brightlayer-ui'

    - package-ecosystem: 'npm'
      directory: '/routing-typescript'
      schedule:
          interval: 'monthly'
          day: 'monday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'
          - 'brightlayer-ui'
